### PR TITLE
HTML table styling to match vd

### PR DESCRIPTION
**Pull request by lkhrs**

### CODE REVIEW

**Comment by saulpw** [comment]
Looks nice, but the keystrokes are too big, e.g.: https://deploy-preview-67--distracted-goldwasser-45d076.netlify.app/docs/navigate/

Also I'm wondering about a double line at the right edge of the last column..:)

**Comment by lkhrs** [comment]
Added in the double-border in 88a9d38, let me know what you think!

**Comment by saulpw** [comment]
> Added in the double-border in [88a9d38](https://github.com/visidata/visidata.org/commit/88a9d388a2a1bc1c0496b87a6a0e406a96115bae), let me know what you think!

Hm, for some reason the tables are now *not* the same width, and so the double-line is always flush with the blue border...

**Comment by lkhrs** [comment]
> > Added in the double-border in [88a9d38](https://github.com/visidata/visidata.org/commit/88a9d388a2a1bc1c0496b87a6a0e406a96115bae), let me know what you think!
> 
> Hm, for some reason the tables are now _not_ the same width, and so the double-line is always flush with the blue border...

Just pushed a789a946cb1f01ec9516aa2b8ec489f4613170f2, is this closer to what you're describing?

**Review by saulpw — APPROVED** [review]

**Pull request merged**
